### ISSUE TITLE
I'm sorry if this isn't the right place to ask you

### ISSUE THREAD

**Issue by zuke119** [z3ugma/z3ugma.github.io#1]
Hi, I was playing around with your "Pay your parking ticket" with a Python API and really like it. I was wondering if you ever DID end up creating code to pay the tickets. Sorry if this isn't the right place, I couldn't find another way to contact you.

**Comment by z3ugma** [comment]
Oh hey, I'm glad you liked it! Still working on this as SaaS platform, actually. Haven't written the code to _pay_ the tickets but it would be very similar to what is posted on my blog. I'd probably use something like [mechanize](https://mechanize.readthedocs.io/en/latest/) to emulate a browser and submit bank acct details to different cities' payment sites. You could do it for your own local city, I'd love to see your solution.
